version: "3.8"
services:
  app:
    image: hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.13_2.13.3
    ports: 
      - 8080:8080
    volumes: 
      - .:/app
      - ~/.ivy2:/home/sbtuser/.ivy2
      - ~/.sbt:/home/sbtuser/.sbt
      - ~/.cache:/home/sbtuser/.cache
    working_dir: /app
    depends_on: 
      - postgres
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: doobie
      POSTGRES_PASSWORD: doobie
